apiVersion: v1
kind: Service
metadata:
  name: image-consumer
  namespace: image-pipeline
spec:
  selector:
    app: image-consumer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
